# wrangler.toml
name = "tron-usdt-transfer-bot"
compatibility_date = "2025-11-14"
compatibility_flags = ["nodejs_compat"]
main = "index.js"

[[dependencies]]
package = "tronweb"

[triggers]
crons = ["*/10 * * * *"]
