# wrangler.toml
name = "tron-transfer-worker-bot1"
compatibility_date = "2025-11-14"
compatibility_flags = ["nodejs_compat"]
main = "index.js"

[[dependencies]]
package = "tronweb"

[triggers]
crons = ["*/10 * * * *"]
